"""Delete Record, add answered_question to user

Revision ID: 145c26dc4ae6
Revises: d0ace9ec613f
Create Date: 2023-12-25 17:44:34.902224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145c26dc4ae6'
down_revision = 'd0ace9ec613f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_questions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    op.drop_table('record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_questions')
    # ### end Alembic commands ###
