"""empty message

Revision ID: 9a2d870510ee
Revises: 
Create Date: 2023-12-21 17:42:37.437295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2d870510ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=350), nullable=True),
    sa.Column('first_option', sa.String(length=100), nullable=True),
    sa.Column('second_option', sa.String(length=100), nullable=True),
    sa.Column('third_option', sa.String(length=100), nullable=True),
    sa.Column('fourth_option', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('questions')
    # ### end Alembic commands ###
